server:
  port: 8082
spring:
  application:
    name: Billing-Worker
  datasource:
    url: jdbc:postgresql://localhost:5433/worker
    username: postgres
    password: loveable
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true